version: "3.4"

services:
  backend:
    build: backend
    image: android.azurecr.io/backend
    restart: "no"
    volumes:
      - ./backend/:/app
    command: /wait-for-it.sh database-server:5432 -- deno run --unstable --watch --allow-net --allow-read --allow-write --allow-env --no-check app.js
    ports:
      - 80:80
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-server
    image: postgres
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:9.8.1-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
